export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const USER_SOCKETS = "USER_SOCKETS";
export const USER_SOCKETS_SUCCESS = "USER_SOCKETS_SUCCESS";
